### PR TITLE
Made changes requested by group

### PR DESCRIPTION
**Pull request by cocochrane**
@virgodi I believe I made all the changes you requested in #16!

### CODE REVIEW

**Comment by virgodi** [comment]
Hey!

Im sorry to tell you that but none of the tests are working :( are you sure you pulled our changes?

**Comment by virgodi** [comment]
For instance, since your test files are now in a sub-sub directory, the path you appended is not the correct one anymore.

**Comment by virgodi** [comment]
As for the databases test, im getting these errors:

`ts1 = pickle.load(open("GeneratedTimeseries/Timeseries"+str(i), "rb"))
/Users/virgileaudi/Desktop/cs207project/timeseries/Similarity/pick_vantage_points.py:52: ResourceWarning: unclosed file <_io.BufferedReader name='GeneratedTimeseries/Timeseries294'>`

**Comment by cocochrane** [comment]
Ah what is happening! I definitely pulled your changes (although jack91an did make changes while I was working on the code) and all the tests were passing (I haven't seen any of those errors before). I'll look into it.

**Comment by virgodi** [comment]
Thanks and sorry for the late changes !

**Comment by cocochrane** [comment]
Actually, two questions:
1. I believe I pulled the new changes from master? But should I pull them from dev? If so, any idea how to do that?

2. When you say "For instance, since your test files are now in a sub-sub directory, the path you appended is not the correct one anymore.", I have no idea where I would have appended a path that needs to be changed?

Thanks!

**Comment by virgodi** [comment]
So pulling you just need to precise: git pull origin dev

and at the start of all your files, you have this: sys.path.append() line. The path you give in when directly in similarity folder, brings you one level up and so you find series.py but if you are in a subdirectory of similarity, it only brings you in similarity where you can't find series.py !

**Comment by cocochrane** [comment]
Ah I see. I'm wondering why I'm having no trouble with that (path file stuff) on my computer- anyway thanks and I'll get back to you

**Pull request merged**
