### PR TITLE
Similarity Code 

### PR DESCRIPTION
**Pull request by cocochrane**
Hi All! Here is an overview of the files attached (all of them are within the "Similarity" folder):

BinarySearchDatabase.py: From lab 10, with the addition of 3 methods (an in-order traversal, a find nodes greater than key function and a find nodes less than key function)
distances.py: where the kernel coefficient, tsmaker, and distance function live
find_most_similar.py: finds the n most similar time series, command line program
generate_time_series.py: generates 1000 time series
pick_vantage_points.py: picks vantage points and creates databases
test_database.py: some tests for the database functions I added
test_similarity: some tests for the similarity functions. Note that I included my sanity_check function which checks the answers using a pure brute force method.
vp: stores the numbers of the vantage points
Folders: GeneratedTimeseries and VantagePointDatabases hold the generated time series and databases, respectively.

Let me know if you have any questions at all (i.e. if there are places that I should document better) or if anything seems off!

### CODE REVIEW

**Comment by virgodi** [comment]
Hey ! I wanted to open a git issue but I can't seem to add you to it so I invited you as a read only participant so that I could tag you !

In the meantime I have a few things for you to work on :P:

1.  Can you write a short Readme to clearly explain in which order files should be called in, and how, if they have any arguments?

2. Could you have the vantage_point script take as argument a integer that rules the number of vantage points desired (we might want to change 20)

3. Could you try to separate all the test files in a subdirectory?

4. Could you have the vp file be saved in one of the data folder? I'm not a big fan of data files flying around.

5. Could you save the time series not as a numpy file but as a proper ArrayTimeSeries using pickle?

6. And finally this might be the longest point. My understanding of the "command line" was that we are supposed to be able to call `python find_similar.py FILENAME` and have the results printed back (or even if you could save them in a pickle file even better). Although your method is much fancier I agree, we won't be able to use it in a bash script later on (i'm thinking ahead for the next part of the project). I think that would be a better fit for us. Do you mind implementing these changes?

Thanks and sorry for the late notice !

Let me know if you need anything from us !

V

**Comment by virgodi** [comment]
Also we made some changes to our time series interface in master. you might want to pull these first and make sure your test still runs !

**Comment by cocochrane** [comment]
@virgodi Hey question about #6. So do you want to be able to do "python find_similar.py FILENAME" or python find_similar.py FILENAME num_files_to_return"? I.e. where do you want the user to specify the number of similar files to return?

**Comment by virgodi** [comment]
yeah that'd be great ! In my implementation, we also give the user the possibility of just printing the results, or indicating a path to the file where we want the results to be saved ±

**Pull request merged**
